export const LANG_ES_NAME = 'es';

export const LANG_ES_TRANS = {
    'ERROR': 'An error has occurred',
    'LOADING_MESSAGE': 'Loading data from server, please wait...',
    'ACCESS': 'Access',
    'LOGIN': 'Login',
    'USERNAME': 'Username (your email)',
    'USERNAME_IS_REQUIRED': 'Username is required',
    'USERNAME_IS_NOT_VALID': 'Username is not valid, valid format put phone number E.g. XXXXXXXXX',
    'PASSWORD': 'Password',
    'PASSWORD_IS_REQUIRED': 'Password is required',
    'BAD_CREDENTIALS': 'Bad credentials',
    'CONTACTS': 'Contacts',
    'CONTACTS_NO_FOUND': 'Contacts no found',
    'NAME': 'Name',
    'PHONE_NUMBER': 'Phone Number',
    'REFRESH': 'Refresh',
    'TYPE': 'Type',
    'DATE': 'Date',
    'CONTACT': 'Contact',
    'CLOSE': 'Close',
    'CALL': 'Call',
    'SMS': 'sms',
    'DIRECTION': 'Direction',
    'INCOMING': 'Incoming',
    'OUTGOING': 'Outgoing',
    'ACTION': 'Action',
    'VIEW': 'View',
    'DURATION': 'Duration'
};
